apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deployment
  labels:
    app: demo-voting-app
spec:
  template:
    metadata:
      name: worker-app-pod
      labels:
        name: worker-app-pod
        app: demo-voting-app
    spec:
      containers:
        - image: dockersamples/examplevotingapp_worker
          name: worker-app
  replicas: 1
  selector:
    matchLabels:
      name: worker-app-pod
      app: demo-voting-app
